[Variables]

; If you want to add task view, the path is [explorer shell:::{3080F90E-D7AD-11D9-BD98-0000947B0257}]
; and the image is tabs.png

; If you want to add file explorer, the path is [explorer shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]
; and the image is file.png

; To add a custom icon move it to the @Resources > Icons Folder
; PNG is needed.

;To change folders they are at the bottom of the file

UserIcon=UserIcon.png

___________________Start Menu________________

Name1=Edge
LocationPath1=["C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"]
Icon1=Microsoft Edge.png

Name2=Gmail
LocationPath2=["https://mail.google.com/mail/"]
Icon2=Mail.png

Name3=photoshop
LocationPath3=["C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop"]
Icon3=photoshop.png

Name4=chrome
LocationPath4=["C:\Program Files\Google\Chrome\Application\chrome.exe"]
Icon4=chrome.png

Name5=Brave
LocationPath5=["C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"]
Icon5=Brave.png

Name6=spotify
LocationPath6=["C:\Users\%username%\AppData\Roaming\Spotify\Spotify.exe"]
Icon6=spotify.png

Name7=Discord
LocationPath7=["C:\Users\%username%\AppData\Local\Discord\app-#DiscordVersion#\Discord.exe"]
Icon7=Discord.png

Name8=Instagram
LocationPath8=["https://www.instagram.com"]
Icon8=Instagram.png

Name9=Facebook
LocationPath9=["https://facebook.com/"]
Icon9=Facebook.png

Name10=youtube
LocationPath10=["https://www.youtube.com/"]
Icon10=youtube.png

___________________Folders___________________

Name11=Computer
LocationPath11=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]
Icon11=Computer.png

Name12=Recycle Bin
LocationPath12=[Shell:::{645FF040-5081-101B-9F08-00AA002F954E}]
Icon12=Recycle Bin.png

Name13=Downloads
LocationPath13=[Shell:::{374DE290-123F-4565-9164-39C4925E467B}]
Icon13=Downloads.png

Name14=Pictures
LocationPath14=[Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]
Icon14=Pictures.png

Name15=Documents
LocationPath15=[Shell:::{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}]
Icon15=Documents.png

Name16=Videos
LocationPath16=[Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}]
Icon16=Videos.png
