[Variables]

; If you want to add task view, the path is "#@#\Applications\TaskView.lnk"
; and the image is tabs.png

; If you want to add file explorer, the path is "#@#\Applications\Explorer.lnk"
; and the image is file.png

; You can not change the start menu path.

; To add a custom icon move it to the @Resources > Icons Folder
; PNG is needed.
___________________Taskbar___________________

StartMenuIcon=Start Button.png

TaskbarIcon2=file.png
Path2="#@#\Applications\Explorer.lnk"

TaskbarIcon3=Microsoft Edge.png
Path3=msedge.exe

TaskbarIcon4=Mail.png
Path4="#@#\Applications\Mail.lnk"

TaskbarIcon5=Word.png
Path5="#@#\Applications\Word.lnk"

TaskbarIcon6=Excel.png
Path6="#@#\Applications\Excel.lnk"

TaskbarIcon7=PowerPoint.png
Path7="#@#\Applications\PowerPoint.lnk"