[Variables]

; If you want to add task view, the path is [explorer shell:::{3080F90E-D7AD-11D9-BD98-0000947B0257}]
; and the image is tabs.png

; If you want to add file explorer, the path is [Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]
; and the image is file.png

; You can not change the start menu path.

; To add a custom icon move it to the @Resources > Icons Folder, and put it in there
; PNG is needed.
___________________Taskbar___________________

StartMenuIcon=Start Button.png

TaskbarIcon2=file.png
Path2=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

TaskbarIcon3=Microsoft Edge.png
Path3=msedge.exe

TaskbarIcon4=Mail.png
Path4=["#@#\Application\Mail.lnk"]

TaskbarIcon5=Word.png
Path5=["#@#\Application\Word.lnk"]

TaskbarIcon6=Excel.png
Path6=["#@#\Application\Excel.lnk"]

TaskbarIcon7=PowerPoint.png
Path7=["#@#\Application\PowerPoint.lnk"]